### ISSUE TITLE
Icons on the left side of the panel are shrinked.

### ISSUE THREAD

**Issue by shamoi** [germanfr/railway-cinnamon#3]
The icons on the left side of the panel are shrinked. I've tried both compiled from source and the one from the Themes menu and same issue occurs.

A quick explanation about where I can find  the logs / files needed for debugging in this bug report would be appreciated :)

**Comment by germanfr** [comment]
Can you post a screenshot of the problem?

**Comment by shamoi** [comment]
[Here](https://ibb.co/k3rVey)

It started doing this after the last update. The only workaround I found is to use an older version which I have a backup of if needed, to compare.

**Comment by germanfr** [comment]
I don't think that is a theme issue. What is that applet? Does it happen with other themes? Can you post a screenshot with the default theme?

**Comment by shamoi** [comment]
It is the CinnVIIStark applet, just with a custom icon. I use CobiWindowsList also.

**Comment by shamoi** [comment]
[Screenshot](https://ibb.co/hv5Rmd) with the CinnVIIStark applet removed and the default Railway theme. And no, this doesn't happen with other themes.

**Comment by germanfr** [comment]
I've found out that the window list applet you are using (CobiWindowList) is actively stretching the icons because it forces the container to be square, and I'm using a padding on it to separate the icon from the label in the default window list applet so proportions are lost there. That is something I do to maintain backwards compatibility with Cinnamon < 3.6 users, and I will eventually remove it. 

In the meantime you can increase you panel height a bit (that solves the issue). It would be a waste of time to ask the applet developer to fix that, since this is something awkward that won't have to be done in the future anymore.

**Comment by shamoi** [comment]
Good! You can close the issue. I will still use both applet, it works great on my side with the older version.  Thank you for the quick support and explanation.
